name: Documentation Deployment
run-name: Deploying to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install mkdocs pymdown-extensions mkdocs-material
      - run: mkdocs gh-deploy --force